version: '3.7'
networks:
  webapp:
    name: webapp
x-defaults: &defaults
  restart: '${DOCKER_RESTART_POLICY}'
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "10m"
services:
  traefik:
    <<: *defaults
    restart: unless-stopped
    image: 'traefik:v2.4'
    container_name: traefik
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
      - '12345:12345'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik/traefik.yml:/etc/traefik/traefik.yml'
      - './traefik/config.yml:/etc/traefik/config.yml'
      - './certs:/etc/certs'
    labels:
      - traefik.enable=true
      - traefik.docker.network=webapp
      - traefik.http.routers.traefik-secure.service=api@internal
      - 'traefik.http.routers.traefik-secure.rule=HostRegexp(`${TRAEFIK_HOST}`)'
      - 'traefik.http.routers.traefik-secure.entrypoints=http,https'
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik.service=api@internal
      - 'traefik.http.routers.traefik.rule=HostRegexp(`${TRAEFIK_HOST}`)'
      - traefik.http.routers.traefik.entrypoints=http
    networks:
      - webapp
  catchall:
    <<: *defaults
    restart: '${DOCKER_RESTART_POLICY}'
    image: 'nginx:alpine'
    container_name: catchall
    labels:
      - traefik.enable=true
      - traefik.docker.network=webapp
      - traefik.http.routers.catchall.entrypoints=http
      - 'traefik.http.routers.catchall.rule=HostRegexp(`{host:.+}`)'
      - traefik.http.routers.catchall.priority=1
      - traefik.http.routers.catchall-secure.entrypoints=https
      - 'traefik.http.routers.catchall-secure.rule=HostRegexp(`{host:.*}`)'
      - traefik.http.routers.catchall-secure.priority=1
      - traefik.http.routers.catchall-secure.tls=true
    networks:
      - webapp
    volumes:
      - './catchAll/html:/usr/share/nginx/html'
      - './catchAll/nginx:/etc/nginx/conf.d'

  mailhog:
    <<: *defaults
    image: mailhog/mailhog:latest
    container_name: mailhog
    hostname: mailhog
    restart: '${DOCKER_RESTART_POLICY}'
    environment:
      - "MH_HOSTNAME=${MAILHOG_HOSTNAME}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webapp"
      - "traefik.http.routers.mailhog.rule=Host(`${MAILHOG_HOSTNAME}`)"
      - "traefik.http.routers.mailhog.entrypoints=http"
      - "traefik.http.routers.mailhog.middlewares=redirect-http-to-https@internal"
      - "traefik.http.routers.mailhog-secure.rule=Host(`${MAILHOG_HOSTNAME}`)"
      - "traefik.http.routers.mailhog-secure.entrypoints=https"
      - "traefik.http.routers.mailhog-secure.tls=true"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    networks:
      - webapp
    volumes:
      - mailhog-data:/var/mailhog/maildir

volumes:
  mailhog-data:
